name: pingjoebox

on:
  schedule:
    - cron: '*/10 * * * *'  # This runs every 10 minutes
  workflow_dispatch:        # Allows manual triggering of the workflow from the Actions tab
  
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Frontend
        run: |
          curl -I https://joebox.onrender.com
